### ISSUE TITLE
Impossibility to push my commit

### ISSUE THREAD

**Issue by jcassoumounat** [KAIST-IS521/backdoor-jcassou#1]
I can't push my commit and I don't know why...
Git told me that everything is up-to-date but one of my file won't be commited....

**Comment by sangkilc** [comment]
Did you add the file? ```git add <file>```

**Comment by jcassoumounat** [comment]
Absolutely, I did git add .

**Comment by sangkilc** [comment]
Why don't you show the error message then.

**Comment by jcassoumounat** [comment]
The problem is that there is no error message. Git tells me that everything is up-to-date...

jean@jean-Inspiron-13-7359:~/Documents/KAIST/Information Security/Activities/backdoor-jcassou$ git add .
jean@jean-Inspiron-13-7359:~/Documents/KAIST/Information Security/Activities/backdoor-jcassou$ git commit
Sur la branche master
Votre branche est en avance sur 'origin/master' de 27 commits.
  (utilisez "git push" pour publier vos commits locaux)
rien à valider, la copie de travail est propre
jean@jean-Inspiron-13-7359:~/Documents/KAIST/Information Security/Activities/backdoor-jcassou$ git push https://github.com/KAIST-IS521/backdoor-jcassou.git
warning: push.default n'est pas défini ; sa valeur implicite a changé dans Git 2.0
de 'matching' vers 'simple'. Pour supprimer ce message et maintenir
le comportement actuel après la modification de la valeur de défaut, utilisez :

  git config --global push.default matching

Pour supprimer ce message et adopter le nouveau comportement maintenant, utilisez :

  git config --global push.default simple

Quand push.default vaudra 'matching', git poussera les branches locales
sur les branches distantes qui existent déjà avec le même nom.

Depuis Git 2.0, Git utilise par défaut le comportement plus conservatif 'simple'
qui ne pousse la branche courante que vers la branche distante correspondante
que 'git pull' utilise pour mettre à jour la branche courante.
 
Voir 'git help config' et chercher 'push.default' pour plus d'information.
(le mode 'simple' a été introduit dans Git 1.7.11. Utilisez le mode similaire
'current' au lieu de 'simple' si vous utilisez de temps en temps d'anciennes versions de Git)

Username for 'https://github.com': jcassou 
Password for 'https://jcassou@github.com': 
Everything up-to-date
jean@jean-Inspiron-13-7359:~/Documents/KAIST/Information Security/Activities/backdoor-jcassou$

**Comment by sangkilc** [comment]
Your last command: ```$ git push https://github.com/KAIST-IS521/backdoor-jcassou.git``` is wrong. You need to set up your remote repo as origin, and type ```git push -u origin master```.

**Comment by jcassoumounat** [comment]
Thank you for your advice but unfortunately, the problem stays the same : the folder 'test' that I created won't be committed.

jean@jean-Inspiron-13-7359:~/Documents/KAIST/Information Security/Activities/backdoor-jcassou$ git push -u origin master
Username for 'https://github.com': jcassou
Password for 'https://jcassou@github.com': 
La branche master est paramétrée pour suivre la branche distante master depuis origin.
Everything up-to-date
jean@jean-Inspiron-13-7359:~/Documents/KAIST/Information Security/Activities/backdoor-jcassou$

**Comment by sangkilc** [comment]
That's because you did not add the file. Use -f option to do so: ```git add -f test/<your file>```.

**Comment by jcassoumounat** [comment]
Thank you very much, that was the problem !
